### ISSUE TITLE
fTOPSIS rank sorts result in an opposite way

### ISSUE THREAD

**Issue by pesikj** [jwieckowski/pyfdm#1]
I am trying to use the module and found out there may be a bug in the `fTOPSIS` method when the weights are given as fuzzy numbers.

In the code below, alternative 2 is superior to alternative 1 in all criteria.

```py
matrix = np.array([
    [[6, 7, 8],[4, 5, 6],[1, 2, 3]],
    [[7, 8, 9],[7, 8, 9],[5, 6, 7]],
])

weights = np.array([[5, 7, 9], [7, 9, 9], [3, 5, 7]])
types = np.array([1, 1, 1])

results = []
for name, method in f_methods.items():
    if name == 'fVIKOR':
        results.append(rank(method(matrix, weights, types)[0], descending=False))
    else:
        results.append(rank(method(matrix, weights, types)))

print(tabulate(np.array(results).T, headers=list(f_methods.keys())))
```

This is the output given by the code.

```py
  fARAS    fCODAS    fEDAS    fMABAC    fMAIRCA    fTOPSIS    fVIKOR
-------  --------  -------  --------  ---------  ---------  --------
      2         2        2         2          1          1         2
      1         1        1         1          2          2         1
```

I checked the preferences.

```py
method = methods.fTOPSIS()
print(method(matrix, weights, types))
```

```py
[0.557 0.539]
```

The preference value of the first alternative is higher than the preference value of the second alternative. But it should be the opposite, as alternative 2 is better in all criteria.

The ranks are opposite (and correct) when the weights are given as numbers.
```py
weights = np.array([1/3, 1/3, 1/3])
```

**Comment by jwieckowski** [comment]
Hi Jiří,

Thank you for your comment and for reporting the issue.
I am looking for the reason for the mentioned behavior in the Fuzzy TOPSIS method calculation.

The possible reason is that the Fuzzy TOPSIS method first normalizes the decision matrix, then the multiplication of the weights and normalized decision matrix is performed. The Ideal Solution in the Fuzzy TOPSIS method is set to Triangular Fuzzy Number (1, 1, 1). At the same time, the multiplied values in the decision matrix are greater than the Ideal Solution for the weights described by you in the comment above. 

I'll let you know when the issue will be solved.

**Comment by jwieckowski** [comment]
Hi Jiří, @pesikj,

I noticed that in the reference paper given in the package documentation, the authors that proposed the Fuzzy TOPSIS method used the criteria weights represented as TFN in the range of 0 - 1. Based on this, using normalized criteria weights in the evaluation process is recommended, as indicates state-of-the-art.

Nevertheless, I will include the mechanism that will normalize criteria weights if the weights given by the user are greater than 1. 

Thank you for your comment once again.

I assume that the issue is solved.

**Comment by pesikj** [comment]
Hi @jwieckowski,

thank you for the analysis. I believe using normalized criteria is ok for me.

Best regards
Jiří
